### PR TITLE
Modification: Milling Sacrificial Layer Settings (r0.93 & pardoc merged)

### PR DESCRIPTION
**Pull request by billgertz**
# Overview
Proposed modification adds the new general settings category _Milling_
and the _Sacrificial Layer Thickness_ setting. Modification addressed
Maintenance leveling routines to account for a higher bed height than
on heated bed side of the build platform. This modification has been
tested with my FABtotum, and seems to work. However more testing would
be prudent. 

__NOTE: Both release 0.93 and pardoc's manual bed leveling python code
cleanup have rolled into this pull request.__

# Files Modified
* fabui/application/config/layout.php
Added jquery.number plugin for Settings in-place browser floating point
number formatting.

* fabui/application/layout/assets/js/plugin/jquery-number/jquery.number.mi
n.js
Added jquerry.number plugin for in-place number formatting (see:
https://github.com/customd/jquery-number).

* fabui/application/modules/settings/ajax/general.php
Added milling sacrificial layer offset form server post processing.

* fabui/application/modules/settings/settings.php
Added loading milling sacrificial layer offset from json printer
config file.

* fabui/application/modules/settings/view/index/general/index.php
Added Milling category and Sacrificial Layer Offset parameter to
browser view.

* fabui/application/modules/settings/view/index/general/index.php
Added jquery.number for in-place formatting of disengage offset and
proposed milling sacrificial layer offset fields to browser view. Aim to
replace default unicode formatted json printer config file using
JSON_NUMERIC_CHECK option in PHP json_encode calls. Rids us of the
python float casts littered throughout the codebase as python will pick
up numerics as float during dictionary dictionary accesses into json
encoded data.

* fabui/python/manual_bed_lev.py
Modification for milling sacrificial layer offset. Without the offset
the bed leveling script brings the bed far too close for the probe to
fully extend. Pardoc's code cleanup has been merged into this pull
request.
__WARNING!: 
Probe points 2 and 3 have been moved 10 mm in +y to avoid breaking
the probe in the sacrificial layer attachment slots. Code review needed!__

# Rational for Beautifier
PHP code has been run through php-cs-fixer to beautify code.
Normalizing code  blocks may be a bit of nitpicking but it does make
the code easier to grok.

### CODE REVIEW

**Comment by wtangent** [comment]
thanks for your contribution!
Testing it - Possibly merging in the next release.

**Comment by billgertz** [comment]
Hey Marco,

I've already gone through the pain of back porting the pull for the current
version. I'll recind my old and post the new. The new port tests fine on
our kit. You should see it this evening or Monday morning.

-Bill

**Comment by billgertz** [comment]
Marco,

No need to recind, it looks like the changes to the pull request made it through my latest mangling.

**Comment by billgertz** [comment]
Marco,

Repeat of forum post:

The pull request has been remerged?, backmergered?, ugh modified for the changes introduced to v0.9485. Have a look and get back to me with any mods needed or problems noted.

New:

I’ve tested it with both your Maintenance Calibration and a modified version of procrash's Advanced Bed Leveling plugin <http://forum.fabtotum.cc/attachment.php?attachmentid=322&d=1418436472>. If pro crash is still active then I’ll go ahead with a pull request to his plugin.


Kind Regards/ Met vriendelijke groet/ Mit freundlichen Grüßen,

Bill Gertz
Senior Consultant
bill.gertz@blockfish.net

Office   	+31 345 511 370
Mobile 	+31 6 422 37005
VoIP	+1 719 207 8777
Skype	bill.gertz

Blockfish BV | Markt 12A | 4101BX | Netherlands
www.blockfish.net

**Comment by kriosmane** [comment]
Added on version 0.9495

**Pull request closed without merging**
